### ISSUE TITLE
textsecure.go doesn't honor logging levels set by config

### ISSUE THREAD

**Issue by selfbc** [signal-golang/textsecure#14]
If you look at textsecure.go on line 268, it sets the logging level to debug regardless of what has been set in the config file.  The proper code has been commented out for unknown reasons.  This causes all kinds of stuff to be in the logs, without any control over it other than manually editing the library code after pulling it down.

**Comment by nanu-c** [comment]
fixed by 62c9aad1b62ffff9fbecaf70007509f1b2175489
