### ISSUE TITLE
Missing / in commit c4ec2205937bdc7f86443c7d5e30baed6f06b646 causes attachments to fail

### ISSUE THREAD

**Issue by selfbc** [signal-golang/textsecure#23]
Hi, in the latest commit (c4ec2205937bdc7f86443c7d5e30baed6f06b646) the initial "/" are missing in the following:
	ATTACHMENT_KEY_DOWNLOAD_PATH = "attachments/%s"
	ATTACHMENT_ID_DOWNLOAD_PATH  = "attachments/%d"
	ATTACHMENT_UPLOAD_PATH       = "attachments/"

These should be as follows:
	ATTACHMENT_KEY_DOWNLOAD_PATH = "/attachments/%s"
	ATTACHMENT_ID_DOWNLOAD_PATH  = "/attachments/%d"
	ATTACHMENT_UPLOAD_PATH       = "/attachments/"

The initial missing "/" causes the URL to be "https://cdn2.signal.orgattachments/", which causes attachments to fail.

**Comment by morph027** [comment]
Oh, thanks for the finding. Do you want to start a PR yourself? Or should i take care of?

**Comment by selfbc** [comment]
Got a bit going on today, so feel free.  Thanks for all of your hard work!

**Comment by selfbc** [comment]
Done, see https://github.com/signal-golang/textsecure/pull/24
