### ISSUE TITLE
Release v1.3.1 libzkgroup_linux_amd64.so needed

### ISSUE THREAD

**Issue by Hetti** [signal-golang/textsecure#40]
Just compiled the latest release from today and encountered that the library is missing on the system, which the tool wants

`/usr/bin/signal: error while loading shared libraries: libzkgroup_linux_amd64.so: cannot open shared object file: No such file`

and therefore don't want to start.

I just got back to Release v.1.2.14 https://github.com/signal-golang/textsecure/releases/tag/v1.2.14 and this works flawlessly and doesn't need this library.

Any Ideas?
Thanks

**Comment by morph027** [comment]
You can download it from here: https://github.com/nanu-c/zkgroup/releases/tag/v0.8.1

**Comment by morph027** [comment]
```
curl -L -o /lib/x86_64-linux-gnu/libzkgroup_linux_amd64.so https://github.com/nanu-c/zkgroup/releases/download/v0.8.1/libzkgroup-linux_x86_64-v0.8.1.so
ldconfig
```

**Comment by Hetti** [comment]
Thanks!
I'm wondering, why the library wasn't extra needed in the v.1.2.14 release as it also used this library? :-)

Thanks for explaining :)

**Comment by nanu-c** [comment]
libzkgroup was added to support the new group system of signal and this is a go wrapper around the original openwhisper zkgroup lib that is written in rust and compiled a shared lib. Everything is new and we are improving.

**Comment by nanu-c** [comment]
But it's also mentioned in the readme :) https://github.com/signal-golang/textsecure/tree/master/cmd/textsecure#cannot-find-library

**Comment by Hetti** [comment]
Ah, thank you very much, I totally oversaw this! =)

closing this issue
