### ISSUE TITLE
contacts on armhf devices

### ISSUE THREAD

**Issue by huggymann** [signal-golang/textsecure#41]
Hello, 

contacts are not working on armhf devices due to an issue with the 64bit conversion in a calculation. Please see this issue about details: https://github.com/nanu-c/axolotl/issues/381

Solution already mentioned to change line  https://github.com/signal-golang/textsecure/blob/master/contactDiscoveryCrypto/contactDiscoveryCrypto.go#L104 

to 
`strconv.ParseInt(s, 10, 64)`

**Comment by huggymann** [comment]
i did a build already and checked on the armhf device oneplus one. 

I am not allowed to push to the repo, could someone please include this change?

**Comment by nanu-c** [comment]
Cool, i will include it in the next release!
