### ISSUE TITLE
Not support for arm64

### ISSUE THREAD

**Issue by WildSaoFeng** [signal-golang/textsecure#50]
Undefined symbols for architecture arm64:
  "_FFI_AuthCredentialPresentation_checkValidContents", referenced from:
      __cgo_23d06c6dc298_Cfunc_FFI_AuthCredentialPresentation_checkValidContents in _x002.o
     (maybe you meant: __cgo_23d06c6dc298_Cfunc_FFI_AuthCredentialPresentation_checkValidContents)

**Comment by nanu-c** [comment]
it does support arm64 and armv7 so in order to help you i need more information what you did.

**Comment by nanu-c** [comment]
Feel free to open a new issue with a better description
