### ISSUE TITLE
ed25519/extra25519 change of repositories

### ISSUE THREAD

**Issue by pieterbork** [signal-golang/textsecure#7]
While trying to get this project up and running, I see that https://github.com/agl/ed25519 is now deprecated and has moved to https://github.com/golang/crypto/tree/master/ed25519. 

For now, I've forked the original project https://github.com/pieterbork/ed25519 and this project https://github.com/pieterbork/textsecure and changed all of the imports to build successfully. However, it seems like the correct solution is to point at the official crypto/ed25519 repo, but I'm not sure what to do about extra25519 as it is imported multiple times in textsecure and doesn't seem to be present in crypto/ed25519.

**Comment by morph027** [comment]
Hi!

Thanks for reporting. I've picked up your fork for now, but we should switch to the internal packages soon (will create another issue for this).

**Comment by pieterbork** [comment]
Still seeing an import from github.com/agl/ed25519 in 
https://github.com/signal-golang/textsecure/blob/master/axolotl/curves_test.go, let me know once you change that and I'll try testing out a build.

**Comment by morph027** [comment]
Ah, that one slipped ;) Fixed it..

**Comment by pieterbork** [comment]
That did the trick, thanks! I'll still be using my version of textsecure that outputs received messages to redis so I can both produce and consume message with python. Not sure if there is interest in having that as an option in this repo, seems to work well in conjunction with signal-web-gateway stuff you've done here. Let me know if that sounds useful and I can create a MR.

**Comment by morph027** [comment]
Uh, sounds interesting. It's this commit, right? https://github.com/pieterbork/textsecure/commit/c93b7d8895a99c223c7ae0a46cb51f9a1734af06

Guess we should add a boolean commandline param like i did for hook and/or gateway, one for the redis host, one for the port, one for the db ...

**Comment by nanu-c** [comment]
For me it's okay to add it if it's documented somwhere :)
